version: '3.8'

services:
  audio-enhancer:
    build: .
    container_name: audio-enhancer-service
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./models:/app/models
    environment:
      - WORKER_COUNT=2
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - audio-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: audio-enhancer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - audio-enhancer
    networks:
      - audio-network
    profiles:
      - production

networks:
  audio-network:
    driver: bridge
